# Generated by Django 5.1.7 on 2025-03-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='captcha',
        ),
    ]
